site_name: Whatsfly Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true
          docstring_style: sphinx
nav:
  - Home: index.md
  - "Api Reference":
    - "Whatsapp Class Reference": apireference.md
    - "Events Types Reference": eventsreference.md
